### ISSUE TITLE
XML format for ELAS depths?

### ISSUE THREAD

**Issue by twadleigh** [AndreiBarsan/DynSLAM#51]
I am trying to preprocess some extra KITTI odometry sequences for DynSLAM. I've gotten so far as to be able to generate the dispnet-based depths and the MNC-based semantic segmentation masks, and can run DynSLAM with the right combination of flags.

I'd like to be able to also generate and use ELAS-based depths. I have cloned https://github.com/AndreiBarsan/libelas-tooling and have been able to get to the point where I can have `kitti2klg` create a directory of `.ppm` and `.pgm` files. However, it appears that DynSLAM expects to find the ELAS depths in an XML format.

I have combed through the various processing scripts to find clues for the right way to perform that last step of the conversion, but haven't found anything. Any hints?

**Comment by AndreiBarsan** [comment]
These were generated using OpenCV's FileStorage interface which writes XML. See: https://docs.opencv.org/2.4/modules/core/doc/xml_yaml_persistence.html
