### ISSUE TITLE
could not find processing-kitti-tracking.sh

### ISSUE THREAD

**Issue by miaohuiqi** [AndreiBarsan/DynSLAM#53]
I'm sorry, when I run your project, I failed at the step of preprocessing, the  'process-kitti-tracking.sh'  file dose not exist. I don't kow how to download or find it. Looking forword for your answer! Thank you very much

**Comment by AndreiBarsan** [comment]
This may have been because I hadn't pushed everything from the subrepos. Can you try again?

**Comment by AndreiBarsan** [comment]
I think this should be solved at this time, so I'm closing the issue. Please feel free to reopen if you're still having issues, thank you!!
