### ISSUE TITLE
error: Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by zgxsin** [AndreiBarsan/DynSLAM#54]
Hi, there was an error when I updated the submodules in this project:

error: Server does not allow request for unadvertised object 44345855a7a3adbe167cdc3957884ebbd6ec15ae
Fetched in submodule path 'preprocessing/dispnet-flownet-docker', but it did not contain 44345855a7a3adbe167cdc3957884ebbd6ec15ae. Direct fetching of that commit failed.

I checked the path in the .gitmodule file and it is correct. Any ideas?

**Comment by zgxsin** [comment]
@AndreiBarsan Did you make local changes in the submodule dispnet-flownet-docker and forget to push to the forked repo? This might the source of the problem.

**Comment by AndreiBarsan** [comment]
Hi, sorry for the delay, just got around to checking this. I pushed some changes; can you try now?
