### ISSUE TITLE
can't clone due to dependencies on non-public eigen repository

### ISSUE THREAD

**Issue by catphive** [AndreiBarsan/DynSLAM#55]
When trying to do:
git clone --recursive https://github.com/AndreiBarsan/DynSLAM

It fails to download because the eigen submodule on github is either private or no longer exists:

fatal: Authentication failed for 'https://github.com/RLovelett/eigen/'

Is there something special about this eigen repository? Can we just replace it with any eigen mirror on github?

**Comment by AndreiBarsan** [comment]
No. I don't think there's anything special about that mirror. No idea why it's there..
I'll update the repo, but in the meantime could you try, e.g.: https://github.com/eigenteam/eigen-git-mirror/releases/tag/3.3.7 ?

**Comment by AndreiBarsan** [comment]
Seems like this was due to someone making their repo private. I fixed the dependency to a public mirror!
