### ISSUE TITLE
link to sample dataset broken

### ISSUE THREAD

**Issue by catphive** [AndreiBarsan/DynSLAM#56]
I'd like to try out the sample pre-processed dataset in the readme. However, the link seems to be broken:

http://www.cs.toronto.edu/~iab/dynslam/mini-kitti-odometry-seq-06-for-dynslam.7z

Is there anywhere I can get this dataset now? I'm planning to use DynSlam as part of a class project.

**Comment by AndreiBarsan** [comment]
Ah, bad timing, sorry, I was changing some stuff on my website.
I put it on my Drive for now: https://drive.google.com/open?id=1V-I4Tle7MNbmnf2qRe6aTpjxOld2M2i8
