### ISSUE TITLE
i can't find the file "process-kitti-tracking.sh"

### ISSUE THREAD

**Issue by jingresume** [AndreiBarsan/DynSLAM#58]
when i want to run 
```
scripts/preprocess-sequence.sh kitti-tracking ~/datasets/track/data training 6
```
I have encountered such a problem
```
Running dispnet preprocessing script!
scripts/preprocess-sequence.sh: line 199: ./process-kitti-tracking.sh: No such file or directory
Failure: Could not build or run DispNet on sequence ID [6] under path: [/home/jing/datasets/track/data/training]

```
i think it because missing this file "scripts/preprocess-sequence.sh"
please tell me how to download it?
thank you very much!

**Comment by AndreiBarsan** [comment]
Ah, darn, do you have anything in the `preprocessing/dispnet-flownet-docker` directory? Can you run `git submodule update --init --recursive` in the main project dir?

**Comment by AndreiBarsan** [comment]
Hi, I'll assume you solved this for now, so I'll be closing the issue. Feel free to re-open if you have further questions! Thank you!
