### ISSUE TITLE
Could I complie InfiniTAM separately?

### ISSUE THREAD

**Issue by MicroYY** [AndreiBarsan/DynSLAM#59]
I only want to use the depth fusion part.     I have tried but cannot make it.

**Comment by AndreiBarsan** [comment]
Have you tried looking at the main InfiniTAM repository: https://github.com/victorprad/InfiniTAM ?
It has lots of great instructions for building, and they've even updated it a lot over the version I used in DynSLAM so it supports stuff like loop closure now, too, which aren't in DynSLAM.
