### ISSUE TITLE
compile on jetson nano, got error!

### ISSUE THREAD

**Issue by jcyhcs** [AndreiBarsan/DynSLAM#65]
hi,professor:
i compile your code in nvidia jetson nano platform,then i got an error:
/home/nvidia/DynSLAM/src/DynSLAM/InstRecLib/../../libviso2/src/matcher.h:30:10: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.

how can i resolve this problem? PLEASE HELP ME!

**Comment by AndreiBarsan** [comment]
This response is a bit late but hopefully it helps others in the future. Your error is related to the compiler you are using. Based on Googling it seems it cannot find an include file for some headers containing aliases for SIMD instructions.

The processor Jeston Nano is ARM-based, while this project has only been developed and tested for x86 processors like Intel and AMD ones. Unfortunately libviso2, a key dependency of this project, has some hardcoded SIMD parts which are unlikely to compile on ARM out of the box.
